apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - image: vynnykv/node-app-kuber:0.1
        name: node-app
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 80